spring.application.name=DemoChatbox

spring.datasource.url=jdbc:postgresql://localhost:5432/demochatbox
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.thymeleaf.cache=false

app.seed.enabled=true
app.chat.ai-name=Noi That Assistant
